Algoritmo "Multiplicação"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Natali Schers
// Data atual  : 05/05/2020
Var
// Seção de Declarações das variáveis 
a, b, r: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a<-10
b<-5
escreval ("Programa da Multiplicação")
escreval ("O Valor de A é:", a)
escreval ("O Valor de B é", b)
 r<-a*b
 escreva ("A Multiplicação de A e B é:", r)

Fimalgoritmo