algoritmo "Programa do par ou ímpar"
// Função : Define se o número é par ou ímpar
// Autor : Natali Schers
// Data : 26/01/2021
// Seção de Declarações 
var
num: inteiro
inicio
// Seção de Comandos 
escreval("PROGRAMA DO PAR OU ÍMPAR")

escreval("Digite um número: ")
leia(num)

se (num%2=0) entao
escreval("O número é par")
senao
escreval("O número é ímpar")
fimse

fimalgoritmo
