algoritmo "Programa da Soma III"
// Função : Soma os números digitados até 0 ser digitado
// Autor : Natali Schers
// Data : 01/09/2020
// Seção de Declarações 
var
soma, num: inteiro
inicio
// Seção de Comandos 
repita
      escreval("Digite um número")
      leia(num)
      soma<-soma+num //acumulador
ate (num=0)
escreval ("A soma dos números digitados é:" , soma)

fimalgoritmo

