algoritmo "Programa da Tabuada"
// Função : Fazer a tabuada do número informado
// Autor : Natali Schers
// Data : 31/08/2020
// Seção de Declarações 
var
num, result, cont: inteiro
inicio
// Seção de Comandos 
escreval("Programa faz a tabuada do valor informado pelo usuário")
escreval("Digite um número: ")
leia(num)

para cont de 1 ate 10 faca
result<- num*cont
     escreval(num,"x",cont,"=",result)
fimpara
fimalgoritmo
