Algoritmo "Volume"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Natali Schers
// Data atual  : 12/05/2020
Var
// Seção de Declarações das variáveis 
r, v: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
v<-3,14159*r*r*altura
r<-12
escreval("O Valor de V é:",v)
escreval("O Valor de R é:", r)
  V<-3,14159*12*12*altura
  escreval("-3,14159*12*12*altura é:", V)
  
Fimalgoritmo